### ISSUE TITLE
Coinbase fee - taken from payment amount...

### ISSUE THREAD

**Issue by ghost** [compumatrix/portal#10]
Something to be aware of (at least in my area)
When sending the "exact amount" asked for, to pay for the Loan (purchase of SilverCard),
Coinbase included the fee in the amount sent - thus when I wanted to Mark as Paid I got the message:
Insufficient funds.
So had to do additional payments...

**Comment by fingrowth** [comment]
My 50 euro cash out took 72 hours. I used Chrome browser.

**Comment by allyinspirit** [comment]
Didn't have this issue using our Australian exchange Coinjar, Inga. ~Ally.

**Comment by compumatrix** [comment]
Noted.
