### ISSUE TITLE
First Cashout Request

### ISSUE THREAD

**Issue by 1detgrl** [compumatrix/portal#11]
Requested 1 BTC August 22nd, 2016     Confirmed August 29th, 2016

Has not reached the blockchain.  Can you please check on this.

**Comment by Lovejoy2** [comment]
Yup, me too and there are a number of Staff members who placed an order on
August 22nd that have still not appeared on the blockchain.

**Comment by herbie24** [comment]
Requested 50 euros on 8/23 still not on blockchain

**Comment by compumatrix** [comment]
We are already checking on this. Cryptofresh appears to be down so we can't seem to get an approval code back to meet the algorithm's requirement.

**Comment by paulabat** [comment]
I have sent through 3 withdrawals as I have paid for two VPC's and to date I have not seen anything on the blockchain.  I was just in Cryptofresh as I was checking on a members information and that appears to be working fine.  I first request was 1BTC on the 8/23 then on the 09/02 and 04/09.  The payments for the VPCs are very quick mine last one only took about two hours.

**Comment by paulabat** [comment]
Mine are now appearing on the Blockchain so that is a start.
