### ISSUE TITLE
15 days gone without transaction showing in blockchain

### ISSUE THREAD

**Issue by greatshare** [compumatrix/portal#12]
It has been 15 days now since I had made a cashout of 1 Bitcoin. The cashout report says 'completed' but no sign of the transaction in the blockchain.

**Comment by compumatrix** [comment]
Please provide more information. You need to provide which account, username and date.

**Comment by greatshare** [comment]
Account : Individual Account of Vijay Kumar Paul. usernsme: greatshare , Account No: 10000073-IN,
Country : India. Date requested : 22 August 2016 for 1 Bitcoin. BTC Address: 347LjPc3NanxedprTB73xCqzXBV5gP4XG9,
