### ISSUE TITLE
Got a issue

### ISSUE THREAD

**Issue by walrusron** [compumatrix/portal#2]
I was sending to 1BVDarDs5TDCwQKPYr6XkMiGWepwPvXgoF and there was no response.

**Comment by compumatrix** [comment]
What do you mean no response? Please provide screenshot.

**Comment by walrusron** [comment]
![screenshot 2016-08-22 09 29 50](https://cloud.githubusercontent.com/assets/20888461/17877326/4f1ed624-6897-11e6-9d3f-718107b3f18a.png)
Cash out did not go to block chain.  TY

**Comment by compumatrix** [comment]
It says transaction complete (The response is on top). This means that your request had been transmitted to tradeceeds for validation and processing.

**Comment by walrusron** [comment]
Henry,
After 7 days, my cash out transaction is still Pending.  What's Next?  Ron

**Comment by compumatrix** [comment]
did they return your funds back?

**Comment by walrusron** [comment]
No, not at this time.

**Comment by walrusron** [comment]
It does show complete now.

**Comment by walrusron** [comment]
I did realize that I had used the same BTC address once before, for a internal transfer in Coinbase.
Just letting you know.
Ron

**Comment by walrusron** [comment]
Enclosed is a copy of my 2 Cash outs. Neither one has gone to the Blockchain.  As of 9/8/2016 AM                                                                                                                                                     09/02/2016 1BHavpgrcwZjbC87TQtRbi49YaLYLU5xuo  ฿ 1.00000000  € 511.32  € 511.32  Completed
08/22/2016  1BVDarDs5TDCwQKPYr6XkMiGWepwPvXgoF  ฿ 0.10000000  € 51.16   € 511.61  Completed
