### ISSUE TITLE
Cashout to DEX 

### ISSUE THREAD

**Issue by coky1** [compumatrix/portal#20]
09/07/2016  cni-coky    ฿ 0.69641148  Completed
Shows completed on portal, but not received in DEX

**Comment by BlueMagic1** [comment]
Same in your case as Boyd's.
Admin log shows it has been processed -

Admin GWalton  09/07/2016   04:54am
Sent Cashout via Openledger for Jorge Francisco Guevara -Zamora

**Comment by coky1** [comment]
Ok, not showing yet. Will wait till Monday or tuesday

**Comment by coky1** [comment]
As promise I waited. No compuceeds were acredited to my OL account (cni-coky)
I checked cryptofresh too
Just reporting.
