### ISSUE TITLE
no btc addy to pay for vpc purchase

### ISSUE THREAD

**Issue by BlueMagic1** [compumatrix/portal#23]
![screenshot](https://cloud.githubusercontent.com/assets/20880459/18612330/b6b5ce76-7d89-11e6-8180-f5f979066b06.png)

No BTC Address where to pay for VPC purchase

**Comment by BlueMagic1** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/20880459/18612502/e33ed650-7d8d-11e6-8f29-7990fd84c5b2.png)

**Comment by coky1** [comment]
Having same problem with a member

**Comment by BlueMagic1** [comment]
Raju Mahtani, UN - Piscis56, has encountered the same error above.

**Comment by BlueMagic1** [comment]
My issue here has been resolved.  Thank you.
