### ISSUE TITLE
Payment for Card

### ISSUE THREAD

**Issue by Lovejoy2** [compumatrix/portal#26]
**another issue
payment for a card .. clicked on confirm (with 52 confirmations on blockchain) and getting payment not confirmed, not only the missing btc addy but also its confirmation link**

**Comment by cniijane-compumatrix** [comment]
Same here .. for a card I purchased  Clicked on mark as paid with  53 confirmations and \ giving back Your payment is not yet confirmed.

**Comment by hubba1** [comment]
Jane, did you try clearing out history and rebooting?  that has worked for a few...

**Comment by BlueMagic1** [comment]
Jane & Liz,

It is now working from my end.  Suggest you try again.  :)

**Comment by cniijane-compumatrix** [comment]
Ok.. worked now after clearing cookies and history.  Thank you

**Comment by hubba1** [comment]
oh good!
