### ISSUE TITLE
Bitcoin address

### ISSUE THREAD

**Issue by herbie24** [compumatrix/portal#27]
No bitcoin address when silver card purchased

**Comment by BlueMagic1** [comment]
Suggest you try checking your Billing tab now, Herb.

**Comment by herbie24** [comment]
Still no bitcoin address there is a code to redeem the card

**Comment by BlueMagic1** [comment]
Oh ok.  Then I guess the issue may not have been resolved in your case.

I had the same problem as yours yesterday and this morning I logged into my Portal, Billing tab and saw the btc addy.
