### ISSUE TITLE
For the first cashout 65 hrs gone but 0.4995 not received

### ISSUE THREAD

**Issue by greatshare** [compumatrix/portal#33]
It has been over 65 hours since I received 0.0005 btc
in my exchanger but 0.4995 btc have still not been received
in my exchanger.

Vijay Kumar Paul' usename - greatshare

**Comment by BlueMagic1** [comment]
i think that is happening to all of us who have requested last Sept 18, except for COO Erline who has posted that she has already gotten hers paid.  Don't know if there are others who haven't reported such full payt though.

**Comment by greatshare** [comment]
Yess there are many others

**Comment by 1detgrl** [comment]
I have not received mine either Vijay.  I expect it will be taken care of over the next 48 hours as per the post in the portal.
